/// Flutter icons Icons
/// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Icons
///      fonts:
///       - asset: fonts/NaraIcons.ttf
///
/// 
/// * Elusive, Copyright (C) 2013 by Aristeides Stathopoulos
///         Author:    Aristeides Stathopoulos
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://aristeides.com/
/// * Font Awesome 4, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL ()
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class NaraIcons {
  NaraIcons._();

  static const _kFontFam = 'Icons';
  static const String? _kFontPkg = null;

  static const IconData doc_new = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData print = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
